# Generated by Django 5.1.6 on 2026-01-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name="To'langan"),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd pul'), ('transfer', "Karta o'tkazma")], default='cash', max_length=20, verbose_name="To'lov usuli"),
        ),
    ]
