# Generated by Django 5.1.6 on 2026-03-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_is_paid_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Yetkazish narxi'),
        ),
    ]
