# Generated by Django 5.1.6 on 2026-03-13 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '__first__'),
        ('orders', '0003_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bts_shipment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='bts_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='bts_tracking_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.btscity', verbose_name='Yetkazish shahri'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.btsregion', verbose_name='Yetkazish viloyati'),
        ),
    ]
