# Generated by Django 5.2.10 on 2026-07-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_delivery_zone_alter_orderitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="Buyurtma paytidagi tannarx (muzlatilgan)",
                max_digits=12,
                verbose_name="Tannarx",
            ),
        ),
    ]
