# Generated by Django 5.1.6 on 2026-04-16 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Zona / Tuman')),
                ('fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Yetkazish narxi')),
                ('free_threshold', models.DecimalField(decimal_places=0, default=0, help_text="Buyurtma shu summadan oshsa, yetkazish bepul. 0 — har doim to'lanadi.", max_digits=12, verbose_name='Bepul yetkazish chegarasi')),
                ('estimated_days', models.CharField(blank=True, help_text='Masalan: 1-2 kun', max_length=50, verbose_name='Yetkazish muddati')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='delivery.region', verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': 'Yetkazish zonasi',
                'verbose_name_plural': 'Yetkazish zonalari',
                'ordering': ['region__ordering', 'ordering', 'name'],
                'unique_together': {('region', 'name')},
            },
        ),
    ]
