# Generated by Django 5.1.6 on 2026-03-13 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTSCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bts_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'BTS Shahar',
                'verbose_name_plural': 'BTS Shaharlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BTSRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bts_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'BTS Viloyat',
                'verbose_name_plural': 'BTS Viloyatlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BTSBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bts_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='delivery.btscity')),
            ],
            options={
                'verbose_name': 'BTS Filial',
                'verbose_name_plural': 'BTS Filiallar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='btscity',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='delivery.btsregion'),
        ),
    ]
