# Generated by Django 5.1.6 on 2026-01-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage_image_url_alter_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('emoji', models.CharField(default='💎', help_text='Banner emoji', max_length=10)),
                ('gradient', models.CharField(default='from-amber-500/20 via-amber-600/10 to-transparent', help_text='Tailwind gradient classlari', max_length=200)),
                ('link', models.CharField(blank=True, help_text="Bosilganda o'tish linki", max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
