# Generated by Django 5.1.6 on 2026-03-30 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
    ]
