# Generated by Django 5.2.10 on 2026-06-27 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_image_url_from_productimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="brands/")),
                (
                    "country",
                    models.CharField(
                        blank=True, help_text="Ishlab chiqaruvchi davlat", max_length=80
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Bosh sahifada ko'rsatish"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Brend",
                "verbose_name_plural": "Brendlar",
                "ordering": ["order", "name"],
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="metal_type",
        ),
        migrations.RemoveField(
            model_name="product",
            name="proba",
        ),
        migrations.RemoveField(
            model_name="product",
            name="size",
        ),
        migrations.RemoveField(
            model_name="product",
            name="weight",
        ),
        migrations.AddField(
            model_name="product",
            name="country_of_origin",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="product",
            name="ingredients",
            field=models.TextField(blank=True, help_text="Asosiy tarkib"),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("skincare", "Teri parvarishi"),
                    ("makeup", "Makiyaj"),
                    ("perfume", "Parfyumeriya"),
                    ("haircare", "Soch parvarishi"),
                    ("bodycare", "Tana parvarishi"),
                ],
                default="skincare",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shade",
            field=models.CharField(
                blank=True, help_text="Rang/ton, masalan 'Nude 02'", max_length=80
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shelf_life_months",
            field=models.PositiveIntegerField(
                blank=True, help_text="Yaroqlilik muddati (oy)", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="skin_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("all", "Barcha teri turlari"),
                    ("dry", "Quruq"),
                    ("oily", "Yog'li"),
                    ("combination", "Aralash"),
                    ("normal", "Normal"),
                    ("sensitive", "Sezgir"),
                ],
                default="all",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="volume",
            field=models.CharField(
                blank=True, help_text="Hajm, masalan 50 ml", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="emoji",
            field=models.CharField(
                default="💄", help_text="Banner emoji", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="gradient",
            field=models.CharField(
                default="from-pink-500/20 via-rose-400/10 to-transparent",
                help_text="Tailwind gradient classlari",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="products.brand",
            ),
        ),
    ]
