# Generated by Django 5.2.10 on 2026-07-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0005_brand_remove_product_metal_type_remove_product_proba_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="Yetkazib beruvchidan olingan narx (foyda hisoblash uchun, mijozga ko'rinmaydi)",
                max_digits=12,
                verbose_name="Tannarx",
            ),
        ),
    ]
