# Generated by Django 5.2.10 on 2026-07-29 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_cost_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default=0,
                help_text="Yetkazib beruvchidan olingan narx (foyda hisoblash uchun, mijozga ko'rinmaydi). Bo'sh qoldirilsa 0 hisoblanadi.",
                max_digits=12,
                verbose_name="Tannarx",
            ),
        ),
    ]
